In [5]:
!pip install pandas matplotlib numpy scikit-learn seaborn

Requirement already satisfied: pandas in C:\Users\User\anaconda3\Lib\site-packages (2.2.3)
Requirement already satisfied: matplotlib in C:\Users\User\anaconda3\Lib\site-packages (3.10.0)
Requirement already satisfied: numpy in C:\Users\User\anaconda3\Lib\site-packages (2.1.3)
Requirement already satisfied: scikit-learn in C:\Users\User\anaconda3\Lib\site-packages (1.6.1)
Requirement already satisfied: seaborn in C:\Users\User\anaconda3\Lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\User\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\User\anaconda3\Lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\User\anaconda3\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\User\anaconda3\Lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in C:\Users\User\anaconda3\Lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\User\anaconda3\Lib\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\User\anaconda3\Lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in C:\Users\User\anaconda3\Lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in C:\Users\User\anaconda3\Lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in C:\Users\User\anaconda3\Lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: scipy>=1.6.0 in C:\Users\User\anaconda3\Lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in C:\Users\User\anaconda3\Lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in C:\Users\User\anaconda3\Lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in C:\Users\User\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data_path = 'water_potability.csv'
df_raw = pd.read_csv(data_path)
df = df_raw.copy()

df.head(20)

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0
5,5.584087,188.313324,28748.687739,7.544869,326.678363,280.467916,8.399735,54.917862,2.559708,0
6,10.223862,248.071735,28749.716544,7.513408,393.663396,283.651634,13.789695,84.603556,2.672989,0
7,8.635849,203.361523,13672.091764,4.563009,303.309771,474.607645,12.363817,62.798309,4.401425,0
8,NaN,118.988579,14285.583854,7.804174,268.646941,389.375566,12.706049,53.928846,3.595017,0
9,11.180284,227.231469,25484.508491,9.077200,404.041635,563.885481,17.927806,71.976601,4.370562,0
10,7.360640,165.520797,32452.614409,7.550701,326.624353,425.383419,15.586810,78.740016,3.662292,0
11,7.974522,218.693300,18767.656682,8.110385,NaN,364.098230,14.525746,76.485911,4.011718,0
12,7.119824,156.704993,18730.813653,3.606036,282.344050,347.715027,15.929536,79.500778,3.445756,0
13,NaN,150.174923,27331.361962,6.838223,299.415781,379.761835,19.370807,76.509996,4.413974,0
14,7.496232,205.344982,28388.004887,5.072558,NaN,444.645352,13.228311,70.300213,4.777382,0
15,6.347272,186.732881,41065.234765,9.629596,364.487687,516.743282,11.539781,75.071617,4.376348,0
16,7.051786,211.049406,30980.600787,10.094796,NaN,315.141267,20.397022,56.651604,4.268429,0
17,9.181560,273.813807,24041.326280,6.904990,398.350517,477.974642,13.387341,71.457362,4.503661,0
18,8.975464,279.357167,19460.398131,6.204321,NaN,431.443990,12.888759,63.821237,2.436086,0
19,7.371050,214.496610,25630.320037,4.432669,335.754439,469.914551,12.509164,62.797277,2.560299,0

In [49]:
# statistical summary

display(df.info())
print(f'\nShape: {df.shape}\n')
display(df.describe())
potability_counts = df.groupby('Potability').size()
display(potability_counts)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ph               2785 non-null   float64
 1   Hardness         3276 non-null   float64
 2   Solids           3276 non-null   float64
 3   Chloramines      3276 non-null   float64
 4   Sulfate          2495 non-null   float64
 5   Conductivity     3276 non-null   float64
 6   Organic_carbon   3276 non-null   float64
 7   Trihalomethanes  3114 non-null   float64
 8   Turbidity        3276 non-null   float64
 9   Potability       3276 non-null   int64
dtypes: float64(9), int64(1)
memory usage: 256.1 KB

None

Shape: (3276, 10)

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
count,2785.000000,3276.000000,3276.000000,3276.000000,2495.000000,3276.000000,3276.000000,3114.000000,3276.000000,3276.000000
mean,7.080795,196.369496,22014.092526,7.122277,333.775777,426.205111,14.284970,66.396293,3.966786,0.390110
std,1.594320,32.879761,8768.570828,1.583085,41.416840,80.824064,3.308162,16.175008,0.780382,0.487849
min,0.000000,47.432000,320.942611,0.352000,129.000000,181.483754,2.200000,0.738000,1.450000,0.000000
25%,6.093092,176.850538,15666.690297,6.127421,307.699498,365.734414,12.065801,55.844536,3.439711,0.000000
50%,7.036752,196.967627,20927.833607,7.130299,333.073546,421.884968,14.218338,66.622485,3.955028,0.000000
75%,8.062066,216.667456,27332.762127,8.114887,359.950170,481.792304,16.557652,77.337473,4.500320,1.000000
max,14.000000,323.124000,61227.196008,13.127000,481.030642,753.342620,28.300000,124.000000,6.739000,1.000000

Potability
0    1998
1    1278
dtype: int64

Data Cleaning

In [50]:
# Missing value summary
missing = df.isnull().sum()
missing_percentage = (missing/len(df)*100).round(2)
missing_df = pd.DataFrame({'Missing Count':missing, 'Missing %': missing_percentage})
missing_df = missing_df[missing_df['Missing Count']>0].sort_values('Missing %', ascending=False)
display(missing_df)

                 Missing Count  Missing %
Sulfate                    781      23.84
ph                         491      14.99
Trihalomethanes            162       4.95

In [51]:
df['ph'] = df['ph'].fillna(df['ph'].mean())
df['Sulfate'] = df['Sulfate'].fillna(df['Sulfate'].median())
df['Trihalomethanes'] = df['Trihalomethanes'].fillna(df['Trihalomethanes'].median())

print(df.isnull().sum())

ph                 0
Hardness           0
Solids             0
Chloramines        0
Sulfate            0
Conductivity       0
Organic_carbon     0
Trihalomethanes    0
Turbidity          0
Potability         0
dtype: int64

In [52]:
df.head()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,7.080795,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,333.073546,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,333.073546,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0